engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
ratings:
  paths:
    - "**.css"
    - "**.js"
    - "**.jsx"
exclude_paths:
- "public/bower_components/"
